# Problem is that there are two strings s, t and string t is generated by randomly shuffling string "s" and adding one extra letter anywhere randomly.
# Now, we have to find that extra randomly added element.
# Since, this is guaranteed that there is only one extra element added, then we can make use of XOR trick to find that extra element.
# ex. s = "abcd", t = "abcde"
# S ^ T = "e"
# Time : 0(N), Space : 0(N)

# function to solve above problem using XOR trick

def findTheDifference(self, s: str, t: str) -> str:

    if not len(s) and not len(t):
        return

    # since , XOR works on numbers, hence converting to ASCII form
    count_s = [ord(i) for i in s]
    count_t = [ord(i) for i in t]
    # taking XOR of first string
    res = 0
    for i in count_s:
        res ^= i
    # taking XOR of second string which effectively will cancel out repeated
    # elements and remaining one will be the extra element
    for i in count_t:
        res ^= i
    return chr(res)
