name: Generate and Publish Milestone Document

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  milestone:
    name: Generate and Publish Milestone Document
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Milestone Documentation Generator
        uses: ory/milestone-action@v0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          outputFile: milestones.md
      - name: Commit Milestone Documentation
        uses: EndBug/add-and-commit@v4.4.0
        with:
          message: 'autogen(docs): update milestone document'
          author_name: souravs17031999
          author_email: 'souravs_1999@rediffmail.com'
          new_branch: github-milestone-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
